### ISSUE TITLE
Change the information that when hover sat/b 

### ISSUE THREAD

**Issue by HardenedSteel** [Rucknium/bchmempool#29]
![image](https://user-images.githubusercontent.com/19209715/152843518-725f12ed-b327-4b62-9eb1-9abbf7395657.png)

If needed change calculation of fee.

**Comment by HardenedSteel** [comment]
@Rucknium what is average transaction size for BCH? And is calculation method correct at backend?

**Comment by Rucknium** [comment]
I changed the fiat decimal precision in a couple of places here: https://github.com/Rucknium/bchmempool/commit/52e0dc11883ce6d520c24ef9f007477a2de47921

I suppose that a "typical" transaction is 2-in/2-out, which is about 370 bytes: https://github.com/Rucknium/bchmempool/commit/476b5682f73dc8395e881d33ee716c118b8752d3

I'm not sure if the back end is calculating things right, but changing these lines _did_ change the displayed value: https://github.com/Rucknium/bchmempool/commit/fbfcf7cfeda87ce194fe114d82e82dd6dfa413fb

**Comment by Rucknium** [comment]
Fixed with 52e0dc1 and 476b568
